apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontendd
  namespace: microservices-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: frontendd:latest
          ports:
            - containerPort: 80
          env:
            - name: REACT_APP_API_GATEWAY
              value: "http://gateway-service:3000"
